src/Domain/Feedback/Entity/Feedback.php
<?php

declare(strict_types=1);

namespace Domain\Feedback\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Domain\Shared\Entity\AbstractEntity;
use Domain\Shared\Entity\OwnerTrait;

/**
 * class Feedback.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
class Feedback extends AbstractEntity
{
    use OwnerTrait;

    private ?string $content = null;

    private ?string $status = null;

    private bool $is_read = false;

    private bool $is_anonymous = false;

    private ?string $promotion = null;

    private int $response_count = 0;

    /**
     * @var Collection<FeedbackResponse>
     */
    private Collection $responses;

    public function __construct()
    {
        $this->status = 'PENDING';
        $this->responses = new ArrayCollection();
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isIsRead(): bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getPromotion(): ?string
    {
        return $this->promotion;
    }

    public function setPromotion(?string $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function isIsAnonymous(): bool
    {
        return $this->is_anonymous;
    }

    public function setIsAnonymous(bool $is_anonymous): self
    {
        $this->is_anonymous = $is_anonymous;

        return $this;
    }

    public function getResponses(): Collection
    {
        return $this->responses;
    }

    public function addResponse(FeedbackResponse $response): self
    {
        if (! $this->responses->contains($response)) {
            $this->responses[] = $response;
            $response->setFeedback($this);
        }

        return $this;
    }

    public function removeResponse(FeedbackResponse $response): self
    {
        if ($this->responses->removeElement($response)) {
            if ($response->getFeedback() === $this) {
                $response->setFeedback(null);
            }
        }

        return $this;
    }

    public function getResponseCount(): int
    {
        return $this->response_count;
    }

    public function setResponseCount(int $response_count): self
    {
        $this->response_count = $response_count;

        return $this;
    }

    public function increaseResponseCount(): self
    {
        ++$this->response_count;

        return $this;
    }

    public function decreaseResponseCount(): self
    {
        --$this->response_count;

        return $this;
    }
}

src/Domain/Shared/Entity/TimestampTrait.php
<?php

declare(strict_types=1);

namespace Domain\Shared\Entity;

/**
 * Trait TimestampTrait.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
trait TimestampTrait
{
    protected ?\DateTimeImmutable $created_at = null;

    protected ?\DateTimeImmutable $updated_at = null;

    public function setCreatedAtWithCurrentTime(): void
    {
        if (null !== $this->created_at) {
            $this->created_at = new \DateTimeImmutable();
        }
    }

    public function setUpdatedAtWithCurrentTime(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface|string|null $created_at): self
    {
        $this->created_at = $this->createDateTime($created_at);

        return $this;
    }

    public function createDateTime(\DateTimeInterface|string|null $date): ?\DateTimeImmutable
    {
        if (is_string($date)) {
            $datetime = \DateTimeImmutable::createFromFormat('Y-m-d H:i', $date);

            return false === $datetime ? null : $datetime;
        } elseif ($date instanceof \DateTimeInterface) {
            return \DateTimeImmutable::createFromInterface($date);
        }

        return null;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface|string|null $updated_at): self
    {
        $this->updated_at = $this->createDateTime($updated_at);

        return $this;
    }
}

src/Infrastructure/Feedback/Symfony/Form/CreateFeedbackForm.php
<?php

declare(strict_types=1);

namespace Infrastructure\Feedback\Symfony\Form;

use Application\Feedback\Command\CreateFeedbackCommand;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * class CreateFeedbackForm.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
final class CreateFeedbackForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class, [
                'label' => 'feedback.forms.labels.content',
                'help' => "vous n'avez que 300 caractères pour exprimer votre feedback",
            ])
            ->add('promotion', TextType::class, [
                'label' => 'feedback.forms.labels.promotion',
            ])
            ->add('is_anonymous', CheckboxType::class, [
                'label' => 'feedback.forms.labels.is_anonymous',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CreateFeedbackCommand::class,
            'translation_domain' => 'feedback',
        ]);
    }
}

src/Infrastructure/Feedback/Symfony/Controller/Admin/DashboardController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Feedback\Symfony\Controller\Admin;

use Domain\Feedback\Repository\FeedbackRepositoryInterface;
use Infrastructure\Shared\Symfony\Controller\AbstractController;
use Infrastructure\Shared\Symfony\Controller\ChartTrait;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\UX\Chartjs\Builder\ChartBuilderInterface;

/**
 * class DashboardController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
final class DashboardController extends AbstractController
{
    use ChartTrait;

    #[Route('/admin/feedback/dashboard', name: 'administration_feedback_dashboard', methods: ['GET'])]
    public function index(
        FeedbackRepositoryInterface $repository,
        ChartBuilderInterface $builder
    ): Response {
        $data = $repository->findStats();
        $chart = $this->createDistributionChart($builder, $repository->findCurrentYearFrequency());

        return $this->render(
            view: '@admin/domain/feedback/feedback/dashboard.html.twig',
            parameters: [
                'data' => $data,
                'chart' => $chart,
            ]
        );
    }
}

src/Infrastructure/Feedback/Symfony/Controller/Admin/FeedbackController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Feedback\Symfony\Controller\Admin;

use Application\Feedback\Command\SetFeedbackViewedCommand;
use Domain\Feedback\Entity\Feedback;
use Infrastructure\Feedback\Doctrine\Repository\FeedbackRepository;
use Infrastructure\Shared\Symfony\Controller\AbstractCrudController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * class FeedbackController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('/admin/feedbacks', 'administration_feedback_')]
final class FeedbackController extends AbstractCrudController
{
    protected const DOMAIN = 'feedback';
    protected const ENTITY = 'feedback';

    #[Route('', name: 'index', methods: ['GET'])]
    public function index(FeedbackRepository $repository): Response
    {
        $is_read = $this->request->query->get('is_read', null);

        return $this->render(
            view: $this->getViewPath('index'),
            parameters: [
                'data' => $this->paginator->paginate(
                    target: $repository->findBy(
                        criteria: null !== $is_read ? [
                            'is_read' => $is_read,
                        ] : [],
                        orderBy: [
                            'created_at' => 'DESC',
                        ]
                    ),
                    page: $this->request->query->getInt('page', 1),
                    limit: 50
                ),
            ]
        );
    }

    #[Route("/{id<\d+>}", name: 'show', methods: ['GET'])]
    public function show(Feedback $row): Response
    {
        if (false === $row->isIsRead()) {
            try {
                $this->dispatchSync(new SetFeedbackViewedCommand($row));
            } catch (\Throwable $e) {
                $this->logger->error($e->getMessage(), $e->getTrace());
            }
        }

        return $this->render(
            view: '@admin/domain/feedback/feedback/show.html.twig',
            parameters: [
                'data' => $row,
            ]
        );
    }
}

src/Infrastructure/Feedback/Symfony/Controller/Admin/FeedbackResponseController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Feedback\Symfony\Controller\Admin;

use Application\Feedback\Command\CreateFeedbackResponseCommand;
use Application\Feedback\Command\DeleteFeedbackResponseCommand;
use Application\Feedback\Command\UpdateFeedbackResponseCommand;
use Domain\Feedback\Entity\Feedback;
use Domain\Feedback\Entity\FeedbackResponse;
use Infrastructure\Feedback\Symfony\Form\CreateFeedbackResponseForm;
use Infrastructure\Feedback\Symfony\Form\UpdateFeedbackResponseForm;
use Infrastructure\Shared\Symfony\Controller\AbstractCrudController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * class PostController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('/admin/feedback/response', 'administration_feedback_feedback_response_')]
final class FeedbackResponseController extends AbstractCrudController
{
    protected const DOMAIN = 'feedback';
    protected const ENTITY = 'feedback_response';

    #[Route('/{id}/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Feedback $feedback): Response
    {
        $owner = $this->getUser();

        return $this->executeFormCommand(
            new CreateFeedbackResponseCommand($owner, $feedback),
            CreateFeedbackResponseForm::class
        );
    }

    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(Request $request): Response
    {
        return new RedirectResponse(
            $request->headers->get('referer') ??
                $this->generateUrl('administration_feedback_index')
        );
    }

    #[Route('/{id}', name: 'show', methods: ['GET'])]
    public function show(FeedbackResponse $response): Response
    {
        return $this->redirectToRoute('administration_feedback_show', [
            'id' => $response->getFeedback()?->getId(),
        ]);
    }

    #[Route('/edit/{id<\d+>}', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(FeedbackResponse $row): Response
    {
        //$this->denyAccessUnlessGranted('FEEDBACK_RESPONSE_UPDATE', $row);

        return $this->executeFormCommand(
            command: new UpdateFeedbackResponseCommand($row),
            formClass: UpdateFeedbackResponseForm::class,
            row: $row,
            view: 'edit'
        );
    }

    #[Route('/{id<\d+>}', name: 'delete', methods: ['DELETE'])]
    public function delete(FeedbackResponse $row): Response
    {
        //$this->denyAccessUnlessGranted('FEEDBACK_RESPONSE_DELETE');

        return $this->executeDeleteCommand(new DeleteFeedbackResponseCommand($row), $row);
    }
}

src/Infrastructure/Feedback/Symfony/Controller/Student/FeedbackController.php
<?php

declare(strict_types=1);

namespace Infrastructure\Feedback\Symfony\Controller\Student;

use Application\Feedback\Command\CreateFeedbackCommand;
use Application\Feedback\Command\DeleteFeedbackCommand;
use Application\Feedback\Command\UpdateFeedbackCommand;
use Domain\Feedback\Entity\Feedback;
use Infrastructure\Feedback\Doctrine\Repository\FeedbackRepository;
use Infrastructure\Feedback\Symfony\Form\CreateFeedbackForm;
use Infrastructure\Feedback\Symfony\Form\UpdateFeedbackForm;
use Infrastructure\Shared\Symfony\Controller\AbstractCrudController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * class FeedbackController.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
#[AsController]
#[Route('/profile/feedbacks', 'feedback_')]
final class FeedbackController extends AbstractCrudController
{
    protected const DOMAIN = 'feedback';
    protected const ENTITY = 'feedback';

    #[Route('', name: 'index', methods: ['GET'])]
    public function index(FeedbackRepository $repository): Response
    {
        return $this->render(
            view: '@app/domain/feedback/index.html.twig',
            parameters: [
                'data' => $this->paginator->paginate(
                    target: $repository->findBy([
                        'owner' => $this->getUser(),
                    ], orderBy: [
                        'created_at' => 'DESC',
                    ]),
                    page: $this->request->query->getInt('page', 1),
                    limit: 50
                ),
            ]
        );
    }

    #[Route('/show/{id}', name: 'show', methods: ['GET'])]
    public function show(Feedback $row): Response
    {
        //$this->denyAccessUnlessGranted('FEEDBACK_VIEW');

        return $this->render(
            view: '@app/domain/feedback/show.html.twig',
            parameters: [
                'data' => $row,
            ]
        );
    }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(): Response
    {
        $owner = $this->getUser();
        $command = new CreateFeedbackCommand($owner);
        $turbo = $this->request->headers->get('Turbo-Frame');
        $form = $this->createForm(CreateFeedbackForm::class, $command, [
            'action' => $this->generateUrl('feedback_new'),
        ])->handleRequest($this->request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addSuccessfullActionFlash();

                return $this->redirectSeeOther('feedback_index');
            } catch (\Throwable $e) {
                if ($turbo) {
                    $form->addError($this->addSafeMessageExceptionError($e));
                } else {
                    $this->addSafeMessageExceptionFlash($e);
                    $response = $this->createUnprocessableEntityResponse();
                }
            }
        }

        return $this->render(
            view: '@app/domain/feedback/new.html.twig',
            parameters: [
                'form' => $form,
                '_turbo_frame_target' => $turbo,
            ],
            response: $response ?? null
        );
    }

    #[Route('/edit/{id<\d+>}', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Feedback $row): Response
    {
        //$this->denyAccessUnlessGranted('FEEDBACK_UPDATE', $row);

        $command = new UpdateFeedbackCommand($row);
        $turbo = $this->request->headers->get('Turbo-Frame');
        $form = $this->createForm(UpdateFeedbackForm::class, $command, [
            'action' => $this->generateUrl('feedback_edit', [
                'id' => $row->getId(),
            ]),
        ])->handleRequest($this->request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $this->dispatchSync($command);
                $this->addSuccessfullActionFlash();

                return $this->redirectSeeOther('feedback_index');
            } catch (\Throwable $e) {
                if ($turbo) {
                    $form->addError($this->addSafeMessageExceptionError($e));
                } else {
                    $this->addSafeMessageExceptionFlash($e);
                    $response = $this->createUnprocessableEntityResponse();
                }
            }
        }

        return $this->render(
            view: '@app/domain/feedback/edit.html.twig',
            parameters: [
                'form' => $form,
                '_turbo_frame_target' => $turbo,
            ],
            response: $response ?? null
        );
    }

    #[Route('/{id<\d+>}', name: 'delete', methods: ['POST', 'DELETE'])]
    public function delete(Feedback $row): Response
    {
        //$this->denyAccessUnlessGranted('FEEDBACK_DELETE', $row);

        return $this->executeDeleteCommand(new DeleteFeedbackCommand($row), $row);
    }
}

templates/app/domain/feedback/edit.html.twig
{% extends '@app/shared/layout/survey.html.twig' %}
{% block title 'Édition feedback' %}

{% block form %}
    {% embed "@admin/shared/component/card/_simple.html.twig" %}
        {% block simple_card_body %}
            {% include '@admin/shared/component/_form.html.twig' %}
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/app/domain/feedback/index.html.twig
{% extends '@admin/shared/layout/base.html.twig' %}
{% block title 'Mes feedbacks' %}

{% block header %}
    {% embed '@admin/shared/component/_header.html.twig' %}
        {% block header_title 'Mes feedbacks' %}
        {% block header_action_list %}
            <li>
                <a href="{{ path('feedback_new') }}" class="btn btn-white btn-dim btn-outline-light">
                    {{ 'plus' | icon }}
                    <span>Ajouter un feedback</span>
                </a>
            </li>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% if data | length > 0 %}
        <div class="row g-gs">
            {% for feedback in data %}
                <div class="col-sm-6 col-lg-4 col-xxl-3">
                    {% include '@app/shared/_feedback_card.html.twig' with {feedback: feedback} %}
                </div>
            {% endfor %}
        </div>
        <div class="mt-5 d-flex justify-content-center">
            {% if data is defined %}
                {{ knp_pagination_render(data) }}
            {% endif %}
        </div>
    {% else %}
        <div class="card card-stretch">
            <div class="card-body">
                <div class="d-flex justify-content-center align-center">
                    <div class="nk-block-content nk-error-ld text-center">
                        <img src="{{ asset('images/feedback.svg') }}" alt="aucune données" width="200">
                        <p class="nk-error-description">Vous n'avez aucun feedback</p>
                        <a href="{{ path('feedback_new') }}" class="btn btn-primary">
                            Ajouter un feedback
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/app/domain/feedback/new.html.twig
{% extends '@app/shared/layout/survey.html.twig' %}
{% block title 'Nouveau feedback' %}
{% form_theme form '@admin/shared/layout/form_theme.html.twig' %}

{% block form %}
    {% embed "@admin/shared/component/card/_simple.html.twig" %}
        {% block simple_card_body %}
            <turbo-frame id="form-modal-frame">
                {{ form_start(form, {attr: {'data-turbo-frame': _turbo_frame_target ?? '_top', 'novalidate': 'novalidate'}}) }}
                {% if _turbo_frame_target %}
                    {{ form_errors(form) }}
                {% endif %}

                {{ form_rest(form) }}
                <div class="btn-group">
                    <button class="mt-3 btn btn-primary">
                        {{ 'save-fill' | icon }}
                        <span>{{ 'global.submit' | trans([], 'messages') }}</span>
                    </button>
                    <a href="{{ path('feedback_index') }}" class="mt-3 btn btn-primary">
                        {{ 'comments' | icon }}
                        <span>Mes feedbacks</span>
                    </a>
                </div>
                {{ form_end(form) }}
            </turbo-frame>
        {% endblock %}
    {% endembed %}
{% endblock %}

templates/app/domain/feedback/show.html.twig
{% extends '@admin/shared/layout/base.html.twig' %}
{% block title 'détail du feedback' %}

{% block header %}
    {% embed '@admin/shared/component/_header.html.twig' %}
        {% block header_title 'Feedback' %}
        {% block header_description %}
            <ul class="list-inline">
                <li>ID : <span class="text-base">{{ data.id }}</span></li>
                <li>Date : <span class="text-base">{{ data.createdAt | date('d M Y') }}</span></li>
            </ul>
        {% endblock %}
        {% block header_action_list %}
            <li class="btn-group">
                <a href="{{ path('feedback_index') }}" class="btn btn-white btn-dim btn-outline-light">
                    {{ 'arrow-long-left' | icon }}
                    <span>Mes feedbacks</span>
                </a>
                {% if not data.isRead %}
                    <a href="{{ path('feedback_edit', {id: data.id}) }}" class="btn btn-white btn-dim btn-outline-light">
                        {{ 'edit' | icon }}
                        <span>Modifier</span>
                    </a>
                {% endif %}
            </li>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block content %}
    {% embed '@admin/shared/component/card/_detail.html.twig' %}
        {% import '@admin/shared/component/_macros.html.twig' as _ %}
        {% block detail_card_body %}
            <div class="nk-block">
                <div class="nk-block-head">
                    <h5 class="title">feedback donné le {{ data.createdAt | date('d M Y') }}</h5>
                    <ul class="list-inline mb-3">
                        {% if data.isAnonymous %}
                            <li><span class="badge bg-secondary">feedback anonyme</span></li>
                        {% endif %}
                        {% if data.isRead %}
                            <li><span class="badge bg-primary">feedback lu</span></li>
                        {% endif %}
                        <li><span class="badge bg-secondary">{{ data.responseCount}} réponse</span></li>
                    </ul>
                    <p>{{ data.content }}</p>
                </div>
            </div>

            {% if data.responses | length > 0 %}
                <div class="nk-divider divider md"></div>
                <div class="nk-block">
                    <div class="nk-block-head nk-block-head-sm nk-block-between">
                        <h5 class="title">Réponses</h5>
                    </div>
                    <div class="bq-note">
                        {% for response in data.responses %}
                            {% include '@app/shared/_response.html.twig' with {data: response, feedback: data} %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        {% endblock %}
    {% endembed %}
{% endblock %}